### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by o-rashad**
Implement authentication systems so users can only access areas of a site they are authorized to.

### CODE REVIEW

**Comment by elisha2kyakpo1** [comment]
Hey @od-c0d3r and @tanzila-abedin, I'm currently reviewing your project, and I have just discovered that it's missing important migration files, if you forgot to add them please do that now before I invalidate your project.

**Comment by o-rashad** [comment]
Thanks, @elisha2kyakpo1 for your review. ⭐️
We worked on your review, and migrations should be in place now.

**Review by elisha2kyakpo1 — COMMENTED** [review]
# Status: Invalid Project 👈
Please fix migrations for this project before your make another submission. Do not create another PR.

Happy coding💪

Just in case you have a question about the review, Just mention my name in the comments and I will get a notification.

**Comment by elisha2kyakpo1** [comment]
Check again, it says, you have a duplicate email column, do it before another reviewer invalidates it.

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# INVALID PULL REQUEST :stop_sign: 

## Hello **Team** I am sorry but I have to invalidate your project again for the same reasons as the previous reviewer mentioned.

# HAPPY CODING :computer:

**Comment by o-rashad** [comment]
@GzimAsani Thanks for the review, could you take another look, please?
i was already working on it and still, the issue is not clear enough to know how to fix it.

Thanks

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: REQUIRED CHANGES

@od-c0d3r  Weldone for trying hard to fix the migration issue, however I will suggest that you should delete the whole database and rebuild it, I was able to run your app without migrating the dabase. Amost all requirement passes,here are the changes required from you:
### `create` action
- [x] it makes sure that the user_id for post is the one from the signed_in user ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_create_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
### Its  better  to do this
```ruby
@post = Post.new(post_params)
@post.user_id = current_user.id
```
user_id cannot be passed in params (security)

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔✔**

Hello @od-c0d3r, @tanzila-abedin 

Great work making the required changes👍

You can merge👌👍

Happy coding💻💻

**Comment by o-rashad** [comment]
Thank you @taiwo2, @NtwaliHeritier for the review ⭐⭐

**Pull request merged**
